config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users 

  resources :users do
  	resources :orders, only: [:index, :show] do
      resources :payments, only: [:new, :create]
    end
  end
  
  resources :events do
  	resources :orders
  end
  #resources :orders

  get '*unmatched_route', to: 'application#handle_record_not_found'

  root 'events#index'
end

app/views/shared/_navbar.html.erb
<section class="hero is-primary is-medium">
    <!-- Hero head: will stick at the top -->
    <div class="hero-head">
      <nav class="navbar">
        <div class="container">
          <div class="navbar-brand">
            <%= link_to 'Ticketer', root_path, class: "navbar-item" %>
            <span class="navbar-burger burger" data-target="navbarMenuHeroA">
              <span></span>
              <span></span>
              <span></span>
            </span>
          </div>
          <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end">
              <div class="navbar-item">
                <div class="field is-grouped">
                  <% if user_signed_in? %>
                    <p class="control">
                      <%= link_to "Reservations", user_orders_path(current_user.id) %>
                    </p>
                    <p class="control">
                      <%= link_to current_user.email, edit_user_registration_path %>
                    </p>
                    <p class="control">
                      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                    </p>
                  <% else %>
                    <p class="control">
                      <%= link_to "Log in", new_user_session_path %>
                    </p>
                    <p class="control">
                      <%= link_to "Sign up", new_user_registration_path %>
                    </p>
                  <% end %>
                </div>
              </div>
            </div>
            </div>
          </div>
        </div>
      </nav>
    </div>

  </section>