config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users 

  resources :users do
  	resources :orders, only: [:index, :show] do
      resources :payments, only: [:new, :create]
    end
  end
  
  resources :events do
  	resources :orders
  end
  #resources :orders

  get '*unmatched_route', to: 'application#handle_record_not_found'

  root 'events#index'
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :tickets

	validates_presence_of :name, :date_time, :description
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :get_event, only: [:show, :update, :edit, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@events = Event.all
	end

	def show
		@arr = Array.new
		@event.tickets.select(:ticket_type).distinct.each do |ticket_type|
			tickets_count = 0
			@event.tickets.where(ticket_type: ticket_type.ticket_type).each do |f| 
				tickets_count += f.amount
			end
				@arr.push([ticket_type, tickets_count])
		end
	end

	private

	def get_event
		@event = Event.find(params[:id])
		@event_tickets = @event.tickets#.where(ticket_type: 'normal').select(:amount)
		#@concession_tickets = @event.tickets.where(ticket_type: 'concession').select(:amount)
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="section">
	<div class="container">
		<% @events.each do |event| %>
			<div class="card">
		  <div class="card-content">
		    <div class="media">
		      <div class="media-content">
		        <p class="title is-4"><%= link_to event.name, event  %> Date: <%= event.date_time %></p>
		      </div>
		    </div>
		  </div>
		</div>
		<% end %>
	</div>
</div>

app/views/events/show.html.erb
<section class="section">
	<div class="container">
		<nav class="level">
		  <!-- Left side -->
		  <div class="level-left">
		    <p class="level-item">
		        <strong><%= @event.name %>, Date: <%= @event.date_time%></strong>
		    </p>
		  </div>
		</nav>
		<hr/>

		<div class="content">
			<h3>Event description:</h3>
			<%= @event.description %>
		</div>
	</div>
</section>

<section class="section comments">
	<div class="container">
		<% @arr.each do |ticket| %>
			<h2 class="subtitle is-5"><strong>Ticket type: <%= ticket[0].ticket_type %>, amount: <%= ticket[1] %></strong> tickets left </h2>
		<% end %>
		<%= link_to "Order ticket", new_event_order_path(params[:id]), class: "button is-primary" %>
	</div>
</section>