config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users 

  resources :users do
  	resources :orders, only: [:index, :show] do
      resources :payments, only: [:new, :create]
    end
  end
  
  resources :events do
  	resources :orders
  end
  #resources :orders

  get '*unmatched_route', to: 'application#handle_record_not_found'

  root 'events#index'
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :ticket

	#validation
	validates :user_id, :ticket_id, :bill, :timestamp, :state, :ticket_type,  presence: true
	validates :user_id, numericality: true
	validates :ticket_id, numericality: true
	validates :bill, numericality: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	# before_action :get_order, only: [:show, :update, :edit, :destroy]
	# before_action :check_if_amount_is_zero, only: [:new, :create]
	before_action :get_event, only: [:new, :create]
	before_action :get_tickets, only: [:new, :create]
	before_action :get_ticket_selling_options, only: [:new, :create]
	before_action :check_if_expired

	def index
	end

	def new
		@order = Order.new
	end

	def create
		flash[:alert] = []
		flash[:success] = []
		if order_params[:multiple_tickets_amount] != "" && order_params[:multiple_tickets_amount].to_i % 2 == 0
			@order_multiple_hash = order_params
			@order_multiple_hash[:altogether_tickets_amount] = ""
			@order_multiple_hash[:avoid_one_tickets_amount] = ""
			ticket = @event.tickets.where(:selling_option => "multiple", :ticket_type => order_params[:ticket_type]).first
			@order_multiple_hash[:ticket_id] = ticket.id
			@order_multiple_hash[:bill] = @order_multiple_hash[:multiple_tickets_amount].to_i * ticket.price
			# @order_multiple = Order.new(o_params)
		end

		check_multiple_tickets_order

		if order_params[:altogether_tickets_amount] != "" && @altogether_tickets.where(:ticket_type => order_params[:ticket_type]).first.amount == order_params[:altogether_tickets_amount].to_i
			@order_altogether_hash = order_params
			@order_altogether_hash[:multiple_tickets_amount] = ""
			@order_altogether_hash[:avoid_one_tickets_amount] = ""
			ticket = @event.tickets.where(:selling_option => "altogether", :ticket_type => order_params[:ticket_type]).first
			@order_altogether_hash[:ticket_id] = ticket.id
			@order_altogether_hash[:bill] = @order_altogether_hash[:altogether_tickets_amount].to_i * ticket.price
			# @order_altogether = Order.new(o_params)
		end

		check_altogether_tickets_order

		avoid_one_tickets_amount = @avoid_one_tickets.where(:ticket_type => order_params[:ticket_type]).first.amount
		if order_params[:avoid_one_tickets_amount] != "" && (order_params[:avoid_one_tickets_amount].to_i == avoid_one_tickets_amount || (avoid_one_tickets_amount - order_params[:avoid_one_tickets_amount].to_i >= 2))
			@order_avoid_one_hash = order_params
			@order_avoid_one_hash[:multiple_tickets_amount] = ""
			@order_avoid_one_hash[:altogether_tickets_amount] = ""
			ticket = @event.tickets.where(:selling_option => "avoid one", :ticket_type => order_params[:ticket_type]).first
			@order_avoid_one_hash[:ticket_id] = ticket.id
			@order_avoid_one_hash[:bill] = @order_avoid_one_hash[:avoid_one_tickets_amount].to_i * ticket.price
			# @order_avoid_one = Order.new(o_params)
		end

		check_avoid_one_tickets_order avoid_one_tickets_amount

		orders = [@order_multiple_hash, @order_altogether_hash, @order_avoid_one_hash]
		try_to_save = orders.map { |order| Order.new(order).save }
		
		check_other_stuff try_to_save

		redirect_to user_orders_path(current_user.id)
		# render 'orders/index'
	end


	def check_multiple_tickets_order
		multiple_tickets_amount = @multiple_tickets.where(:ticket_type => order_params[:ticket_type]).first.amount
		if order_params[:multiple_tickets_amount] != "" && (order_params[:multiple_tickets_amount].to_i % 2 != 0 || order_params[:multiple_tickets_amount].to_i > multiple_tickets_amount)
			@order_multiple_hash = nil
			flash[:alert].push("Number of multiple tickets has to be even, and cant be bigger than: #{multiple_tickets_amount}")
		end
	end

	def check_altogether_tickets_order
		altogether_tickets_amount = @altogether_tickets.where(:ticket_type => order_params[:ticket_type]).first.amount
		if order_params[:altogether_tickets_amount] != "" && (altogether_tickets_amount != order_params[:altogether_tickets_amount].to_i || order_params[:altogether_tickets_amount].to_i > altogether_tickets_amount)
			@order_altogether_hash = nil
			flash[:alert].push("You can only buy all at once tickets of type altogether, and cant be bigger than: #{altogether_tickets_amount}")
		end
	end

	def check_avoid_one_tickets_order avoid_one_tickets_amount
		if order_params[:avoid_one_tickets_amount] != "" && ((avoid_one_tickets_amount - order_params[:avoid_one_tickets_amount].to_i) == 1 || order_params[:avoid_one_tickets_amount].to_i > avoid_one_tickets_amount)
			@order_avoid_one_hash = nil
			flash[:alert].push("Avoid one can only be bought so there will be other quantity left than one, and cant be bigger than: #{avoid_one_tickets_amount}")
		end
	end

	def check_other_stuff try_to_save
		if @order_multiple_hash != nil && order_params[:multiple_tickets_amount] != "" &&  try_to_save[0] == false
			Order.new(@order_multiple_hash).save.errors.each do |error|
				flash[:alert].push(error)
			end
		end
		if @order_altogether != nil && order_params[:altogether_tickets_amount] != "" && try_to_save[1] == false
			Order.new(@order_altogether_hash).save.errors.each do |error|
				flash[:alert].push(error)
			end
		end
		if @order_avoid_one != nil && order_params[:avoid_one_tickets_amount] != "" && try_to_save[2] == false
			Order.new(@order_avoid_one_hash).save.errors.each do |error|
				flash[:alert].push(error)
			end
		end

		if try_to_save[0]
			flash[:success].push("Multiple tickets order saved")
		end
		if try_to_save[1]
			flash[:success].push("Altogether tickets order saved")
		end
		if try_to_save[2]
			flash[:success].push("Avoid one tickets order saved")
		end

		if order_params[:multiple_tickets_amount] == "" && order_params[:altogether_tickets_amount] == "" && order_params[:avoid_one_tickets_amount] == ""
			flash[:alert].push("Nothing saved, form empty")
		end
	end

	private
	
	# def get_order
	# 	@order = Order.find(params[:id])
	# end

	def get_event
		@event = Event.find(params[:event_id])
	end

	def get_tickets
		@tickets_type_and_price = Array.new
		@event.tickets.select(:ticket_type, :price).distinct.each do |tickets|
			@tickets_type_and_price.push([tickets.ticket_type, tickets.price])
		end
	end

	def get_ticket_selling_options
		@multiple_tickets = @event.tickets.where(:selling_option => "multiple")
		@altogether_tickets = @event.tickets.where(:selling_option => "altogether")
		@avoid_one_tickets = @event.tickets.where(:selling_option => "avoid one")
		# @tickets_type_selling_option_and_price = @event.tickets#.select(:ticket_type, :selling_option, :amount)#.each do |tickets|
		# 	@tickets_type_and_price.push([tickets.ticket_type, tickets.selling_option, tickets.amount])
		# end
	end

	def check_if_expired
		@orders = Order.where(:user_id => current_user.id).order("created_at DESC")

		@orders.each do |order|
			total_seconds = (Time.now - order.created_at)
			minutes = (total_seconds / 60).floor
		
			if order.state != "paid" && minutes > 15
				order.update(state: "expired")
			end
		end
	end

	# def check_if_amount_is_zero
	# 	if (order_params[:multiple_tickets_amount] != "" && order_params[:multiple_tickets_amount].to_i == 0) || 
	# 		(order_params[:altogether_tickets_amount] != "" && order_params[:altogether_tickets_amount].to_i == 0) || 
	# 		(order_params[:avoid_one_tickets_amount] != "" && order_params[:avoid_one_tickets_amount].to_i == 0)
			
	# 		flash[:alert] = []
	# 		flash[:alert].push("Amount for any type of selling options can't be 0")
	# 		redirect_to user_orders_path(current_user.id)
	# 	end
	# end

	def order_params
		params.require(:order).permit(:user_id, :ticket_id, :bill, :timestamp, :multiple_tickets_amount, :altogether_tickets_amount, :avoid_one_tickets_amount, :ticket_type)
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="section">
<%= simple_form_for ([@event, @order]) do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :timestamp, :value => Time.now %>
  <h2><strong>Order ticket/s for event <%= @event.name %></strong></h2>
  
  <div>
    <div class="field">
      <h2><strong>Tickets prices</strong></h2>
      <% @tickets_type_and_price.each do |ticket| %>
        <p class="subtitle is-6">Ticket type: <%= ticket[0] %>, price: <%= ticket[1] %></p>
      <% end %>
    </div>
  </div>
  </br>
  <div class="field">
    <div class="select">
      <p><strong>Ticket type</strong></p>
      <%= f.select :ticket_type, @tickets_type_and_price.map { |ticket| [ticket[0]] } %>
    </div>
  </div>
  </br>

  <h2><strong>Selling type, and amount left</strong></h2>
  <% @multiple_tickets.each do |ticket| %>
    <h2>Selling option: <%= ticket.selling_option%>, ticket type: <%= ticket.ticket_type %>, amount left: <%= ticket.amount%></h2>
  <% end %>
  <div class="field">
    <div class="control">
      <%= f.input :multiple_tickets_amount,  wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>
  </br>
  <% @altogether_tickets.each do |ticket| %>
    <h2>Selling option: <%= ticket.selling_option%>, ticket type: <%= ticket.ticket_type %>, amount left: <%= ticket.amount%></h2>
  <% end %>
  <div class="field">
    <div class="control">
      <%= f.input :altogether_tickets_amount,  wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>
  </br>
  <% @avoid_one_tickets.each do |ticket| %>
    <h2>Selling option: <%= ticket.selling_option%>, ticket type: <%= ticket.ticket_type %>, amount left: <%= ticket.amount%></h2>
  <% end %>
  <div class="field">
    <div class="control">
      <%= f.input :avoid_one_tickets_amount,  wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>
  </br>

  <!-- i know this is not the right way, but i couldn't get the js to work through app/assets/js/application.js -->
  <script type="text/javascript">
    var elems = [ "#order_multiple_tickets_amount", "#order_altogether_tickets_amount", "#order_avoid_one_tickets_amount" ];
    $.each( elems, function( i, elem ) {
      $(elem).on("keypress keyup blur",function (event) {    
         $(this).val($(this).val().replace(/[^\d].+/, ""));
          if ((event.which < 48 || event.which > 57)) {
              event.preventDefault();
          }
      });
    });
    

    // var amount = parseInt(0);
    // jQuery('#order_multiple_tickets_amount').on('input', function() {
    //   amount = parseInt(0)
    //   if(!isNaN(parseInt($("#order_multiple_tickets_amount").val()))){
    //     amount += parseInt($("#order_multiple_tickets_amount").val());
    //   }
    //   if(!isNaN(parseInt($("#order_altogether_tickets_amount").val()))){
    //     amount += parseInt($("#order_altogether_tickets_amount").val());
    //   }
    //   if(!isNaN(parseInt($("#order_avoid_one_tickets_amount").val()))){
    //     amount += parseInt($("#order_avoid_one_tickets_amount").val());
    //   }
    //   $('#order_amount').val(amount)
    // });
    // jQuery('#order_altogether_tickets_amount').on('input', function() {
    //   amount = parseInt(0)
    //   if(!isNaN(parseInt($("#order_multiple_tickets_amount").val()))){
    //     amount += parseInt($("#order_multiple_tickets_amount").val());
    //   }
    //   if(!isNaN(parseInt($("#order_altogether_tickets_amount").val()))){
    //     amount += parseInt($("#order_altogether_tickets_amount").val());
    //   }
    //   if(!isNaN(parseInt($("#order_avoid_one_tickets_amount").val()))){
    //     amount += parseInt($("#order_avoid_one_tickets_amount").val());
    //   }
    //   $("#order_amount").val(amount)
    // });
    // jQuery('#order_avoid_one_tickets_amount').on('input', function() {
    //   amount = parseInt(0)
    //   if(!isNaN(parseInt($("#order_multiple_tickets_amount").val()))){
    //     amount += parseInt($("#order_multiple_tickets_amount").val());
    //   }
    //   if(!isNaN(parseInt($("#order_altogether_tickets_amount").val()))){
    //     amount += parseInt($("#order_altogether_tickets_amount").val());
    //   }
    //   if(!isNaN(parseInt($("#order_avoid_one_tickets_amount").val()))){
    //     amount += parseInt($("#order_avoid_one_tickets_amount").val());
    //   }
    //   $("#order_amount").val(amount)
    // });
  </script>

  </br>
  <%= f.button :submit, 'Make reservation', class: "button is-primary"  %>
<% end %>
</div>

app/views/orders/index.html.erb
<div class="section">
	<div class="container">
		<% if flash[:success] != nil && flash[:success].count > 0 %>
			<% flash[:success].each do |n| %>
				<%= flash[:success] = n %>
			<% end %>
		<% end %>
		<% if flash[:alert] != nil && flash[:alert].count > 0 %>
			<% flash[:alert].each do |a| %>
				<%= flash[:alert] = a %>
			<% end %>
		<% end %>

		<% current_user.orders.each do |order| %>
			<div class="card">
		  <div class="card-content">
		    <div class="media">
		      <div class="media-content">
		        <p class="title is-4">Order for event: <%= order.ticket.event.name %>, bill: <%= order.bill %></p>
		        <% unless order.multiple_tickets_amount == ""%>
		        	<p>Multiple tickets: <%= order.multiple_tickets_amount %></br>Status: <%= order.state %></p>
		        	<% unless order.state == "paid" || order.state == "expired"%>
		        		<p>Pay: <%= link_to "pay for order", new_user_order_payment_path(current_user.id, order.id), class: "button is-danger" %></p>
		        	<% end %>
		        <% end %>
		        <% unless order.altogether_tickets_amount == ""%>
		        	<p>Altogether tickets: <%= order.altogether_tickets_amount %></br>Status: <%= order.state %></p>
		        	<% unless order.state == "paid" || order.state == "expired" %>
		        		<p>Pay: <%= link_to "pay for order", new_user_order_payment_path(current_user.id, order.id), class: "button is-danger" %></p>
		        	<% end %>
		        <% end %>
		        <% unless order.avoid_one_tickets_amount == ""%>
		        	<p>Avoid one tickets: <%= order.avoid_one_tickets_amount %></br>Status: <%= order.state %></p>
		        	<% unless order.state == "paid" || order.state == "expired" %>
		        		<p>Pay: <%= link_to "pay for order", new_user_order_payment_path(current_user.id, order.id), class: "button is-danger" %></p>
		        	<% end %>
		        <% end %>
		      </div>
		    </div>
		  </div>
		</div>
		<% end %>
	</div>
</div>

app/views/orders/new.html.erb
<%= render 'form' %>